development:
  secret_key_base: ab2ff1f45c1c3ae6ea00d0368f4614ae1e1e09fae8bd8ec9e3ed53753f8eebfa02e97634a9d8ce7f1d7d4a311cf046c50c9b8bca7ce7d27f51b02443466fe6c5
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_bucket_name: <%= ENV['AWS_BUCKET_NAME'] %>

test:
  secret_key_base: dd7cd14e567b441cba6dd854f6390d704ec8023206d32e5ce1843c92802aea19c6b73797c6ce3b4dbdb06d6067086b2c679fba40a3641fd3e6565df88e6214be
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_bucket_name: <%= ENV['AWS_BUCKET_NAME'] %>

staging:
  secret_key_base: 154c9161eb4be455de4360a77e9eb2a39bd66209e44d60c1415b70d9ccc1559bac6c68dfd7abe35e929290d13507af78b68d8c03282ee578e6082d14c270e006
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_bucket_name: <%= ENV['AWS_BUCKET_NAME'] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_bucket_name: <%= ENV['AWS_BUCKET_NAME'] %>
